extends:
  - 'eslint:recommended'
  - 'airbnb-typescript/base'
parserOptions:
  project: './tsconfig.json'
ignorePatterns:
  - 'build/*'
  - '*.js'
env:
  browser: true
  node: true
  jest: true
plugins:
  - 'import'
rules:
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/naming-convention':
    - 'error'
    - selector: 'variable'
      format:
        - 'camelCase'
        - 'PascalCase'
        - 'UPPER_CASE'
      leadingUnderscore: 'allow'
    - selector: 'function'
      format:
        - 'camelCase'
        - 'PascalCase'
    - selector: 'typeLike'
      format:
        - 'PascalCase'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: 'type|_*'
      varsIgnorePattern: '_*'
  class-methods-use-this: 'off'
  consistent-return: off
  func-names: 'off'
  global-require: 'off'
  import/no-cycle: 'off'
  import/prefer-default-export: 'off'
  max-classes-per-file: 'off'
  no-bitwise:
    - 'error'
    - allow:
        - '^'
  no-param-reassign: 'off'
  no-unused-vars: 'off'
  object-curly-newline:
    - 'error'
    - consistent: true
overrides:
  - files:
      - 'tests/*.test.ts'
    rules:
      no-await-in-loop: 'off'
