export const googleSheetSchema = [[
  'Event name',
  'Event director(s)',
  'What kind of event is this?',
  'Which of the following organizations are involved in this event?',
  'Preferred date',
  'Preferred start time',
  'Preferred end time',
  'Estimated Attendance?',
  'Additional Date/Time Notes',
  'Event description',
  'Which org goals does this event fulfill?',
  'Where is your event taking place?',
  'First choice for venue',
  'Second choice for venue',
  'Third choice for venue',
  'Other venue details?',
  'Will you need a projector?',
  'Will you want a recording of your in person event uploaded to the ACM YouTube channel? ',
  'If yes to the previous question, do you have any special recording requests?',
  'Event Link (ACMURL)',
  'Is there a sponsor that will pay for this event?',
  'Will you want a recording of your event uploaded to the ACM YouTube channel?',
  'List emails you would like to add as hosts (@ucsd.edu)',
  'List emails you would like to invite as panelists',
  'Will you want a recording of your event uploaded to the ACM YouTube channel?',
  'What acmurl will you be using for this event?',
  'Are there any other webinar-specific requests you would like to make?',
  'Will your event require funding?',
  'Are you planning on using the menu system for food?',
  'What do you need funding for?',
  'Non-menu system requests: Vendor website or menu',
  'Anything else you would like to let the Finance Team know about your event?',
  'Will your event require marketing?',
  'Any additional comments or requests?',
  'Timestamp',
  'Email Address',
  'BACKUP ONLINE VENUE: Would you like your backup online venue to be a standard Zoom room or Discord?',
  'What ACMURL do you want for the Facebook event page?',
  'BOT_ID',
  'BOT_CHECKSUM',
]];