# Github actions workflow to triger AWS CodeDeploy to automatically deploy Kartana
name: Kartana Deployment

# Trigger deployment when merging or pushing to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Configure AWS Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        # This step will configure the AWS credentials to ensure access to instance
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # This step will trigger AWS Codedeploy to run using the files from the current commit
      - name: Create CodeDeploy Development
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Git_Application \
            --deployment-group-name Deployment_Group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
      

      
      
    


       

